name: ci

on:
  push:
    branches:
      - master
      - main

env:
  APP_NAME: instantviewbot
  DOCKERHUB_REPO: aturret/instantviewbot
#   APP_VERSION: latest

concurrency: 
  group: instantviewbot
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Check commit message
        id: check_message
        run: |
          MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ "$MESSAGE" == *"[github-action]"* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      -
        name: Build and push
        if: steps.check_message.outputs.skip == 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/amd64
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
#             ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
      # -
      #   name: send curl request
      #   run: |
      #     curl -H 'Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}' ${{ secrets.WATCHTOWER_WEBHOOK_URL }}

